# Generated by Django 6.0.4 on 2026-05-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('nlp', 'NLP & Text'), ('cv', 'Computer Vision'), ('tabular', 'Tabular / Classic ML'), ('other', 'Other')], default='other', max_length=20)),
                ('architecture', models.CharField(blank=True, help_text='e.g. DistilBERT, DeBERTa-v3, ResNet', max_length=200)),
                ('framework', models.CharField(blank=True, help_text='e.g. PyTorch, TensorFlow, scikit-learn', max_length=100)),
                ('competition_name', models.CharField(blank=True, max_length=200)),
                ('competition_url', models.URLField(blank=True)),
                ('dataset_description', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('rank', models.CharField(blank=True, help_text='Leaderboard rank, e.g. "112 / 257"', max_length=50)),
                ('score', models.CharField(blank=True, help_text='Leaderboard score', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ml_models/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ml_models.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Model Link',
                'verbose_name_plural': 'ML Model Links',
            },
        ),
    ]
