# Generated by Django 6.0.4 on 2026-07-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji or icon identifier (e.g., 🧑\u200d💻 or fa-graduation-cap)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'About Item',
                'verbose_name_plural': 'About Items',
                'ordering': ['order'],
            },
        ),
    ]
